apiVersion: v1
kind: Pod
metadata:
  name: resources-demo
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      # Soft limit for CPU and memory
      requests:
        memory: "64Mi" # RAM
        cpu: "100m"    # 1/10th of a CPU 100 millicores
      # Hard limit for CPU and memory
      limits:
        memory: "128Mi" # RAM millibytes
        cpu: "150m"    # 1/5th of a CPU 150 millicores
        